import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bitten",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={sora.className} id="body">
        <a
          href="#body"
          className="w-12 h-12 rounded-full bg-[#e93266] flex justify-center items-center text-white fixed bottom-3 right-3 z-50 font-bold">
          &uarr;
        </a>
        {children}
      </body>
    </html>
  );
}
